[project]
name = "1_cloud_run"
version = "0.1.0"
description = "An example Fast MCP server for deployment on Cloud Run"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp==2.13.1",
    "google-adk>=1.23.0",
    "python-dotenv>=1.0.0",
    "google-auth",
    "requests"
]